version: "3.8"
services:
  front:
    container_name: chess_front
    image: chess-front
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    